name: bansos
description: Aplikasi untuk penyaluran bantuan sosial
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_svg: ^0.19.0
  percent_indicator: ^2.1.1
  shared_preferences: ^0.5.10
  firebase_core : ^0.5.0
  cloud_firestore: ^0.14.0+2
  intl: ^0.16.1
  flutter_styled_toast: ^1.4.0+1
  flutter_launcher_icons: "^0.8.0"
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/img/logo.png"

flutter:
  uses-material-design: true
  assets:
   - assets/img/
   - assets/icons/

  fonts:
    - family: Bebas
      fonts:
        - asset: assets/fonts/bebas_regular.otf
        - asset: assets/fonts/bebas_bold.otf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_regular.ttf
        - asset: assets/fonts/poppins_bold.ttf
          weight: 700
